spring.application.name=waxmeltshop

spring.datasource.url=jdbc:postgresql://localhost:5432/waxmeltshop
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
